dubbo:
  ## Base packages to scan Dubbo Component：@com.alibaba.dubbo.config.annotation.Service
  scan:
    basePackages: com.comma.fit
  ## ApplicationConfig Bean
  consumer:
    loadbalance: roundrobin
    timeout: 60000
    check: false
    retries: -1
  application:
    id: authentication-dubbo
    name: authentication-dubbo
    qos-enable: false
  ## RegistryConfig Bean
  registry:
    id: edas
    #address: edas://jmenv.tbsite.net:8080
    address: zookeeper://119.23.152.168:2181

